---
title: "Guilherme"
author: "ME623-27-09-2016"
date: "27 de setembro de 2016"
output: html_document
---

```{r}
#setwd(choose.dir())
ex01 <- read.table("dados2.dat",header = T)
ex01.mds <- aggregate(resp ~ trat,FUN=mean,data=ex01)$resp
ex01.se <- (aggregate(resp ~ trat,FUN=sd,data=ex01)$resp)/sqrt(6)
cbind(ex01.mds, ex01.se)
require(MASS)
par(mfrow=c(1,2))
plot(ex01)
points(ex01.mds, pch = "x", col = 2, cex = 1.5) #marca a média no grafico com "x"
with(ex01, stripchart(resp ~ trat, met = "jitter", vert = T, pch = 19)) #jitter coloca os pontos
points(ex01.mds, pch = 4, cex = 1.5) #indica a média com "x"
arrows(1:9, ex01.mds + ex01.se, 1:9, ex01.mds - ex01.se,
angle = 90, code = 3, length = 0.1) #coloca um erro padrao acima e um abaixo da média no grafico com barras horizontais

bartlett.test(resp ~ trat, data = ex01) #testa se as variancias são iguais

ex01.mod <- aov(resp ~ trat, data = ex01)

ex01.lm <- lm(resp ~ trat, data = ex01)

x <- matrix(data=c(1,0,0,1,0,0,1,1,0,1,1,0,1,0,1,1,0,1),ncol=3,nrow=6,byrow=T)
beta <- c(10,-3,2)
y <- x%*%beta+rnorm(6)
library(MASS)
beta.hat <- ginv(t(x)%*%x)
beta.hat <- beta.hat%*%t(x)%*%y

lm1<-lm(y~x-1)
model.matrix(lm1)


trt <- c(rep(1,2),rep(2,2),rep(3,2))
tau2 <- ifelse(trt==2,1,0)
tau3 <- ifelse(trt==3,1,0)

lm2 <- lm(y~tau2+tau3)
model.matrix(lm2)

#tomando a terceira coluna como referencia

x <- matrix(data=c(1,1,0,
                   1,1,0,
                   1,0,1,
                   1,0,1,
                   1,0,0,
                   1,0,0),ncol=3,nrow=6,byrow=T)
beta <- c(10,-3,2)
y <- x%*%beta+rnorm(6)
library(MASS)
beta.hat <- ginv(t(x)%*%x)
beta.hat <- beta.hat%*%t(x)%*%y

lm1<-lm(y~x-1)
model.matrix(lm1)


trt <- c(rep(1,2),rep(2,2),rep(3,2))
tau2 <- ifelse(trt==1,1,0)
tau3 <- ifelse(trt==2,1,0)

lm2 <- lm(y~tau2+tau3)
model.matrix(lm2)

```


```{r aula29_09_2016}
summary(lm(resp~trat,data = ex01))$coef
```

$\bar{y}$=353.52
  
$\hat{\mu}_1$ = 378.6667  
$\hat{\mu}_2 - \hat{\mu}_1$ = 52.8333  
$\hat{\mu}_3 - \hat{\mu}_1$ = -32.3333  
$\hat{\mu}_4 - \hat{\mu}_1$ = -85.000  
$\hat{\mu}_5 - \hat{\mu}_1$ = -36.83  
$\hat{\mu}_6 - \hat{\mu}_1$ = 27.33  
$\hat{\mu}_7 - \hat{\mu}_1$ = -214.50  
$\hat{\mu}_8 - \hat{\mu}_1$ = 25.17  
$\hat{\mu}_9 - \hat{\mu}_1$ = 37.00  

$$\tau_i = \mu_i - \mu$$ ($\mu_i$ = media tau i / $\mu$ = media geral)  
  
  
$\hat{\tau}_1$ = 25.15  
$\hat{\tau}_2$ = 77.98  
$\hat{\tau}_3$ = -7.18  
$\hat{\tau}_4$ = -59.85  
$\hat{\tau}_5$ = -11.68  
$\hat{\tau}_6$ = 52.48  
$\hat{\tau}_7$ = -189.35  
$\hat{\tau}_8$ = 50.32  
$\hat{\tau}_9$ = 62.15

```{r}

c1 <- contrasts(ex01$trat)
c1[1,1] <- 1
c1[2,1] <- 0
c1[2,2] <- 1
c1[3,2] <- 0
c2 <- matrix(c1,nrow=9,ncol=8)


```



```{r}
c1 <- rbind(c(2, 2, 2, -1, -1, -1, -1, -1, -1), c(2, -1, -1, rep(0,6)), c(0, 1, -1, rep(0, 6)), c(rep(0, 3), c(2, 2, -1, -1, -1, -1)),c(rep(0, 3), c(1, -1), rep(0, 4)), c(rep(0, 5), c(1, 1, -1, -1)),c(rep(0, 5), c(1, -1, 0, 0)), c(rep(0, 5), c(0, 0, 1, -1)))


library(MASS)
c1.ginv <- ginv(c1)

colnames(c1.ginv) <- paste("contr", 1:8, sep = "")

contrasts(ex01$trat) <- c1.ginv
mod1 <- lm(resp ~ trat, data = ex01)
summary(mod1)

aov(mod1)
```


```{r}
ex01co <- data.frame(model.matrix(resp ~ trat, ex01)[, -1])
names(ex01co) <- paste("Contraste", 1:8)
ex01co$resp <- ex01$resp
mod2 <- lm(resp ~ ., data = ex01co)
av2 <- anova(mod2)
av2
aov(mod2)




contrasts(ex01$trat) <- NULL
```


```{r}
with(ex01, pairwise.t.test(resp, trat))


ex01.mod <- aov(resp ~ trat, data = ex01)
ex01.HSD <- TukeyHSD(ex01.mod, ordered = TRUE)
plot(ex01.HSD)

```


